### ISSUE TITLE
Fork Bomb

### ISSUE THREAD

**Issue by apeschel** [caquino/redis-bash#8]
This line has the potential to fork bomb the system.

https://github.com/caquino/redis-bash/blob/master/redis-bash-lib#L40

**Comment by caquino** [comment]
Thanks @apeschel for spotting that the first fix does not work as it uses a sub-shell.

**Comment by caquino** [comment]
@apeschel I've tested the code here and it worked as expected, I will consider this solved for now.
Thanks!
